// Generated by WebFx

module webfx.demo.mandelbrot.math {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports dev.webfx.demo.mandelbrot.math;
    exports dev.webfx.demo.mandelbrot.math.original;

}